/**
 * Real marketing visuals in /public/marketing - all cropped from actual screenshots of the live
 * /demo page (sample data, clearly labeled), not AI-generated or hand-drawn mockups. See the
 * visual-truth-audit commits for why: this file previously pointed at composite images with fake
 * "Championship Bracket" and "Team Sign Up" UI that didn't match the real app.
 */

export const marketingImages = {
  standings: {
    src: "/marketing/lp-public-standings.webp",
    alt: "A real LeaguePour public competition page showing live standings (3-1-0 points system) for a sample venue.",
    width: 800,
    height: 400,
  },
  bracket: {
    src: "/marketing/lp-tournament-bracket.webp",
    alt: "A real LeaguePour single-elimination tournament bracket, generated by the same bracket logic every competition uses, with sample team names.",
    width: 590,
    height: 460,
  },
  qrSignup: {
    src: "/marketing/lp-qr-signup.webp",
    alt: "A real, working LeaguePour QR sign-up code from the demo page.",
    width: 220,
    height: 260,
  },
} as const;
