/** North American cities ordered by distance from Chicago - the outreach sweep list. */
export type OutreachCity = {
  city: string;
  state: string;
  country: "US" | "CA";
  query: string;
};

export const OUTREACH_CITIES: OutreachCity[] = [
  // Ring 1 - Chicago metro & <100 miles
  { city: "Chicago", state: "IL", country: "US", query: "bars in Chicago IL" },
  { city: "Milwaukee", state: "WI", country: "US", query: "bars in Milwaukee WI" },
  { city: "Waukegan", state: "IL", country: "US", query: "bars in Waukegan IL" },
  { city: "Kenosha", state: "WI", country: "US", query: "bars in Kenosha WI" },
  { city: "Racine", state: "WI", country: "US", query: "bars in Racine WI" },
  { city: "Rockford", state: "IL", country: "US", query: "bars in Rockford IL" },
  { city: "Aurora", state: "IL", country: "US", query: "bars in Aurora IL" },
  { city: "Joliet", state: "IL", country: "US", query: "bars in Joliet IL" },
  { city: "Gary", state: "IN", country: "US", query: "bars in Gary Hammond IN" },
  { city: "South Bend", state: "IN", country: "US", query: "bars in South Bend IN" },
  // Ring 2 - 100-250 miles
  { city: "Indianapolis", state: "IN", country: "US", query: "bars in Indianapolis IN" },
  { city: "Madison", state: "WI", country: "US", query: "bars in Madison WI" },
  { city: "Fort Wayne", state: "IN", country: "US", query: "bars in Fort Wayne IN" },
  { city: "Peoria", state: "IL", country: "US", query: "bars in Peoria IL" },
  { city: "Green Bay", state: "WI", country: "US", query: "bars in Green Bay WI" },
  { city: "Appleton", state: "WI", country: "US", query: "bars in Appleton WI" },
  { city: "Springfield", state: "IL", country: "US", query: "bars in Springfield IL" },
  { city: "Grand Rapids", state: "MI", country: "US", query: "bars in Grand Rapids MI" },
  { city: "Lansing", state: "MI", country: "US", query: "bars in Lansing MI" },
  { city: "Toledo", state: "OH", country: "US", query: "bars in Toledo OH" },
  { city: "Detroit", state: "MI", country: "US", query: "bars in Detroit MI" },
  { city: "Ann Arbor", state: "MI", country: "US", query: "bars in Ann Arbor MI" },
  // Ring 3 - 250-500 miles
  { city: "Columbus", state: "OH", country: "US", query: "bars in Columbus OH" },
  { city: "Cleveland", state: "OH", country: "US", query: "bars in Cleveland OH" },
  { city: "Cincinnati", state: "OH", country: "US", query: "bars in Cincinnati OH" },
  { city: "Dayton", state: "OH", country: "US", query: "bars in Dayton OH" },
  { city: "Akron", state: "OH", country: "US", query: "bars in Akron OH" },
  { city: "Louisville", state: "KY", country: "US", query: "bars in Louisville KY" },
  { city: "St. Louis", state: "MO", country: "US", query: "bars in St. Louis MO" },
  { city: "Minneapolis", state: "MN", country: "US", query: "bars in Minneapolis MN" },
  { city: "Des Moines", state: "IA", country: "US", query: "bars in Des Moines IA" },
  { city: "Kansas City", state: "MO", country: "US", query: "bars in Kansas City MO" },
  { city: "Omaha", state: "NE", country: "US", query: "bars in Omaha NE" },
  { city: "Madison", state: "WI", country: "US", query: "bars taverns in Madison WI" },
  { city: "Pittsburgh", state: "PA", country: "US", query: "bars in Pittsburgh PA" },
  { city: "Nashville", state: "TN", country: "US", query: "bars in Nashville TN" },
  { city: "Memphis", state: "TN", country: "US", query: "bars in Memphis TN" },
  // Ring 4 - 500-800 miles
  { city: "Atlanta", state: "GA", country: "US", query: "bars in Atlanta GA" },
  { city: "Charlotte", state: "NC", country: "US", query: "bars in Charlotte NC" },
  { city: "Raleigh", state: "NC", country: "US", query: "bars in Raleigh Durham NC" },
  { city: "Philadelphia", state: "PA", country: "US", query: "bars in Philadelphia PA" },
  { city: "Baltimore", state: "MD", country: "US", query: "bars in Baltimore MD" },
  { city: "Richmond", state: "VA", country: "US", query: "bars in Richmond VA" },
  { city: "Buffalo", state: "NY", country: "US", query: "bars in Buffalo NY" },
  { city: "Dallas", state: "TX", country: "US", query: "bars in Dallas TX" },
  { city: "Fort Worth", state: "TX", country: "US", query: "bars in Fort Worth TX" },
  { city: "Oklahoma City", state: "OK", country: "US", query: "bars in Oklahoma City OK" },
  { city: "Tulsa", state: "OK", country: "US", query: "bars in Tulsa OK" },
  { city: "Little Rock", state: "AR", country: "US", query: "bars in Little Rock AR" },
  { city: "Denver", state: "CO", country: "US", query: "bars in Denver CO" },
  { city: "Colorado Springs", state: "CO", country: "US", query: "bars in Colorado Springs CO" },
  { city: "Knoxville", state: "TN", country: "US", query: "bars in Knoxville TN" },
  { city: "Lexington", state: "KY", country: "US", query: "bars in Lexington KY" },
  { city: "Louisville", state: "KY", country: "US", query: "taverns bars in Louisville KY" },
  // Ring 5 - 800-1200 miles
  { city: "New York", state: "NY", country: "US", query: "bars in New York City NY" },
  { city: "Boston", state: "MA", country: "US", query: "bars in Boston MA" },
  { city: "Washington", state: "DC", country: "US", query: "bars in Washington DC" },
  { city: "Houston", state: "TX", country: "US", query: "bars in Houston TX" },
  { city: "San Antonio", state: "TX", country: "US", query: "bars in San Antonio TX" },
  { city: "Austin", state: "TX", country: "US", query: "bars in Austin TX" },
  { city: "Jacksonville", state: "FL", country: "US", query: "bars in Jacksonville FL" },
  { city: "Tampa", state: "FL", country: "US", query: "bars in Tampa FL" },
  { city: "Orlando", state: "FL", country: "US", query: "bars in Orlando FL" },
  { city: "Miami", state: "FL", country: "US", query: "bars in Miami FL" },
  { city: "New Orleans", state: "LA", country: "US", query: "bars in New Orleans LA" },
  { city: "Baton Rouge", state: "LA", country: "US", query: "bars in Baton Rouge LA" },
  { city: "Albuquerque", state: "NM", country: "US", query: "bars in Albuquerque NM" },
  { city: "Phoenix", state: "AZ", country: "US", query: "bars in Phoenix AZ" },
  { city: "Tucson", state: "AZ", country: "US", query: "bars in Tucson AZ" },
  { city: "Las Vegas", state: "NV", country: "US", query: "bars in Las Vegas NV" },
  { city: "Salt Lake City", state: "UT", country: "US", query: "bars in Salt Lake City UT" },
  // Ring 6 - West Coast & Far regions
  { city: "Portland", state: "OR", country: "US", query: "bars in Portland OR" },
  { city: "Seattle", state: "WA", country: "US", query: "bars in Seattle WA" },
  { city: "Spokane", state: "WA", country: "US", query: "bars in Spokane WA" },
  { city: "Boise", state: "ID", country: "US", query: "bars in Boise ID" },
  { city: "Sacramento", state: "CA", country: "US", query: "bars in Sacramento CA" },
  { city: "San Francisco", state: "CA", country: "US", query: "bars in San Francisco CA" },
  { city: "Oakland", state: "CA", country: "US", query: "bars in Oakland CA" },
  { city: "San Jose", state: "CA", country: "US", query: "bars in San Jose CA" },
  { city: "Los Angeles", state: "CA", country: "US", query: "bars in Los Angeles CA" },
  { city: "San Diego", state: "CA", country: "US", query: "bars in San Diego CA" },
  { city: "Long Beach", state: "CA", country: "US", query: "bars in Long Beach CA" },
  { city: "Fresno", state: "CA", country: "US", query: "bars in Fresno CA" },
  { city: "Anchorage", state: "AK", country: "US", query: "bars in Anchorage AK" },
  { city: "Honolulu", state: "HI", country: "US", query: "bars in Honolulu HI" },
  // Remaining US metros
  { city: "Hartford", state: "CT", country: "US", query: "bars in Hartford CT" },
  { city: "Providence", state: "RI", country: "US", query: "bars in Providence RI" },
  { city: "Manchester", state: "NH", country: "US", query: "bars in Manchester NH" },
  { city: "Burlington", state: "VT", country: "US", query: "bars in Burlington VT" },
  { city: "Portland", state: "ME", country: "US", query: "bars in Portland ME" },
  { city: "Albany", state: "NY", country: "US", query: "bars in Albany NY" },
  { city: "Syracuse", state: "NY", country: "US", query: "bars in Syracuse NY" },
  { city: "Rochester", state: "NY", country: "US", query: "bars in Rochester NY" },
  { city: "Virginia Beach", state: "VA", country: "US", query: "bars in Virginia Beach VA" },
  { city: "Norfolk", state: "VA", country: "US", query: "bars in Norfolk VA" },
  { city: "Greensboro", state: "NC", country: "US", query: "bars in Greensboro NC" },
  { city: "Winston-Salem", state: "NC", country: "US", query: "bars in Winston-Salem NC" },
  { city: "Columbia", state: "SC", country: "US", query: "bars in Columbia SC" },
  { city: "Charleston", state: "SC", country: "US", query: "bars in Charleston SC" },
  { city: "Savannah", state: "GA", country: "US", query: "bars in Savannah GA" },
  { city: "Birmingham", state: "AL", country: "US", query: "bars in Birmingham AL" },
  { city: "Montgomery", state: "AL", country: "US", query: "bars in Montgomery AL" },
  { city: "Huntsville", state: "AL", country: "US", query: "bars in Huntsville AL" },
  { city: "Jackson", state: "MS", country: "US", query: "bars in Jackson MS" },
  { city: "Shreveport", state: "LA", country: "US", query: "bars in Shreveport LA" },
  { city: "El Paso", state: "TX", country: "US", query: "bars in El Paso TX" },
  { city: "Lubbock", state: "TX", country: "US", query: "bars in Lubbock TX" },
  { city: "Wichita", state: "KS", country: "US", query: "bars in Wichita KS" },
  { city: "Topeka", state: "KS", country: "US", query: "bars in Topeka KS" },
  { city: "Lincoln", state: "NE", country: "US", query: "bars in Lincoln NE" },
  { city: "Sioux Falls", state: "SD", country: "US", query: "bars in Sioux Falls SD" },
  { city: "Fargo", state: "ND", country: "US", query: "bars in Fargo ND" },
  { city: "Billings", state: "MT", country: "US", query: "bars in Billings MT" },
  { city: "Missoula", state: "MT", country: "US", query: "bars in Missoula MT" },
  { city: "Cheyenne", state: "WY", country: "US", query: "bars in Cheyenne WY" },
  { city: "Reno", state: "NV", country: "US", query: "bars in Reno NV" },
  // Canada
  { city: "Toronto", state: "ON", country: "CA", query: "bars pubs in Toronto Ontario" },
  { city: "Montreal", state: "QC", country: "CA", query: "bars pubs in Montreal Quebec" },
  { city: "Vancouver", state: "BC", country: "CA", query: "bars pubs in Vancouver BC" },
  { city: "Calgary", state: "AB", country: "CA", query: "bars pubs in Calgary Alberta" },
  { city: "Edmonton", state: "AB", country: "CA", query: "bars pubs in Edmonton Alberta" },
  { city: "Ottawa", state: "ON", country: "CA", query: "bars pubs in Ottawa Ontario" },
  { city: "Winnipeg", state: "MB", country: "CA", query: "bars pubs in Winnipeg Manitoba" },
  { city: "Hamilton", state: "ON", country: "CA", query: "bars pubs in Hamilton Ontario" },
  { city: "Quebec City", state: "QC", country: "CA", query: "bars pubs in Quebec City" },
  { city: "Halifax", state: "NS", country: "CA", query: "bars pubs in Halifax Nova Scotia" },
  { city: "Saskatoon", state: "SK", country: "CA", query: "bars pubs in Saskatoon Saskatchewan" },
  { city: "Regina", state: "SK", country: "CA", query: "bars pubs in Regina Saskatchewan" },
  { city: "Victoria", state: "BC", country: "CA", query: "bars pubs in Victoria BC" },
  { city: "London", state: "ON", country: "CA", query: "bars pubs in London Ontario" },
  { city: "Windsor", state: "ON", country: "CA", query: "bars pubs in Windsor Ontario" },
];
