import Image from "next/image";
import { cn } from "@/lib/utils";
import { marketingImages } from "@/lib/marketing-images";

type LeaguePourRealVisualProps = {
  className?: string;
  /**
   * "hero" - standings + bracket + QR collage, for the homepage hero (biggest, most prominent slot).
   * "bracket" - bracket-focused, for tournament-format pages.
   * "standings" - standings + QR, for discovery/signup-focused pages.
   */
  variant?: "hero" | "bracket" | "standings";
  priority?: boolean;
};

const cardClass = "min-w-0 overflow-hidden rounded-2xl border border-lp-border bg-white shadow-lg shadow-lp-accent/10";

/**
 * Real LeaguePour UI, not an illustration. Every image here is a cropped screenshot of the actual
 * /demo page - the standings table and tournament bracket are the real components
 * (src/components/app/bracket-preview.tsx) rendered with the same bracket-building logic Start
 * Tournament uses, and the QR code is a real, working code generated by the same
 * src/lib/qr.ts#buildQrDataUrl function every venue's real QR code goes through. Sample data only,
 * clearly labeled on /demo itself. Replaces LeaguePourProductMockup, a hand-drawn fake dashboard.
 *
 * Every grid/flex item wrapping an <Image> carries min-w-0: without it, a grid track's default
 * min-width:auto refuses to shrink below the image's intrinsic pixel width (the bracket screenshot
 * is 590px wide), which forced a fixed-width two-column row regardless of viewport and blew out
 * the whole page with horizontal overflow on mobile - caught in the 375px verification pass.
 */
export function LeaguePourRealVisual({ className, variant = "hero", priority = false }: LeaguePourRealVisualProps) {
  if (variant === "bracket") {
    return (
      <div className={cn("relative min-w-0", className)}>
        <div className={cardClass}>
          <Image
            src={marketingImages.bracket.src}
            alt={marketingImages.bracket.alt}
            width={marketingImages.bracket.width}
            height={marketingImages.bracket.height}
            priority={priority}
            className="h-auto w-full"
          />
        </div>
        <p className="mt-3 text-center text-xs font-semibold uppercase tracking-wide text-lp-muted">
          Real bracket from the /demo page - sample data
        </p>
      </div>
    );
  }

  if (variant === "standings") {
    return (
      <div className={cn("grid min-w-0 grid-cols-1 gap-4 sm:grid-cols-[1fr_auto] sm:items-start", className)}>
        <div className={cardClass}>
          <Image
            src={marketingImages.standings.src}
            alt={marketingImages.standings.alt}
            width={marketingImages.standings.width}
            height={marketingImages.standings.height}
            priority={priority}
            className="h-auto w-full"
          />
        </div>
        <div className={cn(cardClass, "w-full max-w-[9rem] sm:w-32 sm:max-w-none md:w-36")}>
          <Image
            src={marketingImages.qrSignup.src}
            alt={marketingImages.qrSignup.alt}
            width={marketingImages.qrSignup.width}
            height={marketingImages.qrSignup.height}
            className="h-auto w-full"
          />
        </div>
      </div>
    );
  }

  // hero: standings on top, bracket + QR below - side by side from sm: up, stacked on phones.
  return (
    <div className={cn("relative min-w-0", className)}>
      <div className={cn(cardClass, "relative z-10")}>
        <Image
          src={marketingImages.standings.src}
          alt={marketingImages.standings.alt}
          width={marketingImages.standings.width}
          height={marketingImages.standings.height}
          priority={priority}
          className="h-auto w-full"
        />
      </div>
      <div className="mt-4 grid min-w-0 grid-cols-1 gap-4 sm:grid-cols-[1fr_auto]">
        <div className={cardClass}>
          <Image
            src={marketingImages.bracket.src}
            alt={marketingImages.bracket.alt}
            width={marketingImages.bracket.width}
            height={marketingImages.bracket.height}
            className="h-auto w-full"
          />
        </div>
        <div className={cn(cardClass, "w-full max-w-[8rem] self-start sm:w-28 sm:max-w-none md:w-32")}>
          <Image
            src={marketingImages.qrSignup.src}
            alt={marketingImages.qrSignup.alt}
            width={marketingImages.qrSignup.width}
            height={marketingImages.qrSignup.height}
            className="h-auto w-full"
          />
        </div>
      </div>
      <p className="mt-3 text-center text-xs font-semibold uppercase tracking-wide text-lp-muted">
        Real LeaguePour UI from the /demo page - sample data, not a real venue
      </p>
    </div>
  );
}
